services:
  lda_server:
    build: 
      dockerfile: lda_server/Dockerfile
      context: .
    ports: 
      - "1354:1354"
    network_mode: bridge

  lda_frontend:
    build:
      dockerfile: lda_frontend/Dockerfile
      context: .
    ports: 
      - "1355:80"
    network_mode: bridge